### ISSUE TITLE
Ensure that we have electric and compressed air pneumatic controllers

### ISSUE THREAD

**Issue by arbrandt** [arbrandt/OPGEE#314] opened 2021-02-04 16:54 UTC
Add electric and compressed air pneumatic controllers
Make sure that smart default turns on these non-leaking options are default when high sulfur gas is used.

**Comment by JSRuthe** [comment] 2021-04-29 15:39
Duplicate of issue #330

**Closed by JSRuthe** 2021-04-29 15:39 UTC
